name:                icfpc2020
version:             0.1.0.0
github:              "nobsun/icfpc2020"
license:             BSD3
author:              "Nobuo Yamashita"
maintainer:          "nobsun@sampou.org"
copyright:           "Copyright: (c) 2020 Nobuo Yamashita"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Experiment

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nobsun/icfpc2020#readme>

dependencies:
- base >= 4.7 && < 5
ghc-options:
- -Wall

flags:
  static:
    description: build statically linked binaries
    default: false
    manual: true

  gui:
    description: build playgui which requires OpenGL related libraries
    default: false
    manual: true

library:
  dependencies:
  - array
  - attoparsec
  - bytestring
  - containers
  - split
  - http-conduit >= 2.3
  - transformers
  - process
  - unix
  - utf8-string >= 1.0
  - JuicyPixels
  exposed-modules:
  - NFEval
  - Interact
  - Message
  - Modulate
  - Send
  - TextParser
  - ImageFile
  - GalaxyTxt
  - GalaxyRun
  - CurlCmd
  - Game
  - GameRun
  - SValue
  - Commander.Breaking
  - Commander.Further
  - Commander.Closer
  - Commander.Shooter
  other-modules:
  - MonadicParser
  - ListDesugar
  - HsLikePrinter
  - Draw
  - Vec
  # - Eval
  source-dirs: src

executables:
  solution:
    main:                solution.hs
    other-modules:       []
    source-dirs:         app-solution
    ghc-options:
    - -rtsopts
    - -threaded
    when:
      - condition: flag(static)
        then:
          ghc-options: -static
          cc-options: -static
          ld-options:
          - -static
          - -pthread
        else: {}
    dependencies:
    - icfpc2020
    - process

  # libcurl からリンクされている krb5 ライブラリの
  # *.a イメージが Debian では提供されていなかったので
  # static link できなかった
  solution-dyn:
    main:                solution-dyn.hs
    other-modules:
    - CurlLib
    source-dirs:         app-solution
    ghc-options:
    - -rtsopts
    - -threaded
    when:
      - condition: flag(static)
        then:
          ghc-options: -static
        else: {}
    dependencies:
    - icfpc2020
    - process
    - curl

  play:
    main:                play.hs
    other-modules:       []
    source-dirs:         app-play
    ghc-options:
    - -rtsopts
    - -threaded
    dependencies:
    - icfpc2020
    - containers
    - optparse-applicative

  play-gui:
    main:                play-gui.hs
    source-dirs:         app-play
    ghc-options:
    - -rtsopts
    - -threaded
    when:
      - condition: flag(gui)
        then:
          buildable: true
          dependencies:
          - icfpc2020
          - containers
          - process
          - curl
          - GLFW-b
          - OpenGL
          - base
          - mtl
          - optparse-applicative
          - pretty
          - stm
          - transformers
        else:
          buildable: false
      - condition: flag(static)
        then:
          ghc-options: -static
        else: {}

tests:
  icfpc2020-test:
    main:                spec.hs
    other-modules:       []
    source-dirs:         test
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - icfpc2020

  icfpc2020-doctest:
    main:                doctests.hs
    other-modules:       []
    source-dirs:         test
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - icfpc2020
    - doctest
